export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const SYNC_FROM_LOCALSTORAGE = 'SYNC_FROM_LOCALSTORAGE';
